
version: '2.1'
services:
    fraud:
      image: postgres:9.6
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=fraud
      volumes: 
        - ./data:/home/data
      ports:
        - 5432:5432
    postgres:
        image: postgres:9.6
        environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
          # To prevent connection issues on restart: https://airflow.readthedocs.io/en/stable/howto/secure-connections.html
          - AIRFLOW_CONN_POSTGRES_DEFAULT=postgres://admin:password@fraud:5432/fraud
          - AIRFLOW__CORE__FERNET_KEY=F5JDrcsof54xWE_CXR93oxe1U341Pncnc1ULJZmJijw=
    webserver:
        image: puckel/docker-airflow:1.10.4
        build:
            context: github.com/puckel/docker-airflow
            args:
                AIRFLOW_DEPS: postgres
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3